apiVersion: v1
kind: service 
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp 
    version: 2.6.1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodeport: 30001
    protocal: TCP
  selector:
      app: myjavaapp
      version: 2.6.1